# ---------- Gradle performance ----------
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.daemon=true
org.gradle.caching=true

# parallel
org.gradle.parallel=false

# Configuration Cache
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

# ---------- Android ----------
android.useAndroidX=true
android.nonTransitiveRClass=true

# ---------- Kotlin performance ----------
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.daemon.jvmargs=-Xmx2048m
