site_name: Securify
site_url: https://rabehx.github.io/Securify/
repo_url: https://github.com/RabehX/Securify
repo_name: RabehX/Securify
site_description: Securify documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Privacy Policy: PRIVACY_POLICY.md
  - Terms of Service: TERMS_OF_SERVICE.md
